apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-application
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gibil.common.labels" . | nindent 4 }}
data:
  application.properties: |-
    # Spring Boot

    # Netex data file path 
    org.gibil.extime.data-file=/tmp/netex_data.zip

    # Logging
    logging.level.root={{ .Values.configMap.data.LOG_LEVEL }}