apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "gibil.common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.common.ingress.host }}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "app.name" . }}
              port:
                number: 80