apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "app.name" . }}-extime-pvc
  labels:
    {{- include "gibil.common.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: extime-data