apiVersion: v2
appVersion: "0.1.0"
description: AVINOR flights real-time information importer
name: gibil
version: 0.1.0
maintainers:
  - name: 'team-ror'
    email: team.rutedata@entur.org
dependencies:
  - name: common
    version: 1.21.1
    repository: "https://entur.github.io/helm-charts"
