common:
  env: prd
  ingress:
    host: gibil.entur.io
  replicas: 1
  container:
    replicas: 1
    maxReplicas: 2

init:
  NETEX_DATA_URL: https://storage.googleapis.com/marduk-prod/outbound/netex/rb_avi-aggregated-netex.zip

configMap:
  enabled: true
  data:
    LOG_LEVEL: INFO

cronJob:
    gcpProject: entur-dev-gcp2