common:
  env: dev
  ingress:
    host: gibil.dev.entur.io
  replicas: 1

init:
  NETEX_DATA_URL: https://storage.googleapis.com/marduk-dev/outbound/netex/rb_avi-aggregated-netex.zip

configMap:
  enabled: true
  data:
    LOG_LEVEL: DEBUG

cronJob:
  gcpProject: entur-dev-gcp2