common:
  env: tst
  ingress:
    host: gibil.staging.entur.io
  replicas: 1

init:
  extimeData: https://storage.googleapis.com/marduk-test/outbound/netex/rb_avi-aggregated-netex.zip

ingress:
  host: gibil.staging.entur.io

configMap:
  enabled: true
  data:
    LOG_LEVEL: INFO