common:
  env: dev
  replicas: 1

init:
  extimeData: https://storage.googleapis.com/marduk-dev/outbound/netex/rb_avi-aggregated-netex.zip

ingress:
  host: gibil.dev.entur.io

configMap:
  enabled: true
  data:
    LOG_LEVEL: DEBUG
