common:
  env: prd
  replicas: 1
  container:
    replicas: 1
    maxReplicas: 1

init:
  extime-data: https://storage.googleapis.com/marduk-prod/outbound/netex/rb_avi-aggregated-netex.zip

ingress:
  host: gibil.entur.io

configMap:
  enabled: true
  data:
    LOG_LEVEL: INFO